In [2]:
import cv2

In [4]:
cap = cv2.VideoCapture(0)

In [5]:
ret , photo = cap.read()

In [11]:
photo.shape

(480, 640, 3)

In [72]:
cv2.imshow('hello',img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
cap.release()

In [74]:
import numpy
import cv2

img2 = numpy.zeros((300,300,3),numpy.uint8)
#img2 = numpy.zeros((300,300,3))
img2[:,0:100] = (255,125,0)
img2[:,100:200] = (0,255,0)
img2[:,200:300] = (255,0,255)
#for i in img[]:
 #   for j in .....................:
    #    ..............................
#for i in ......................:
 #   for j in .....................:
      #  ..............................
cv2.imshow('image',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
for i in img2[:,100:200]:
    for j in i:
        j=128
        
img2

array([[[255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.],
        ...,
        [255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.]],

       [[255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.],
        ...,
        [255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.]],

       [[255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.],
        ...,
        [255., 125.,   0.],
        [255., 125.,   0.],
        [255., 125.,   0.]],

       ...,

       [[255.,   0., 255.],
        [255.,   0., 255.],
        [255.,   0., 255.],
        ...,
        [255.,   0., 255.],
        [255.,   0., 255.],
        [255.,   0., 255.]],

       [[255.,   0., 255.],
        [255.,   0., 255.],
        [255.,   0., 255.],
        ...,
        [255.,   0., 255.],
        [255.,   0., 255.],
        [255.,   0., 255.]],

       [[255.,   0., 255.],
        [255.,   0., 255.],
        [255.,  

In [32]:
img2[:,:,1:3].shape

(300, 200, 2)

In [49]:
img2[100] = [0,255,0]

In [50]:
img2[100]

array([[  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255

In [56]:

import numpy
import cv2

img = numpy.ones((300,300,1),numpy.uint8)*100
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
img2[100] = [155,0,0]

In [75]:
img2 = numpy.zeros((300,300,3),numpy.uint8)
#img2 = numpy.zeros((300,300,3))
img2[:,0:100] = (255,125,0)
img2[:,100:200] = (0,255,0)
img2[:,200:300] = (255,0,255)

In [76]:
img2.shape

(300, 300, 3)

In [77]:
img3 = numpy.zeros((300,300,3),numpy.uint8)
#img2 = numpy.zeros((300,300,3))
img3[0:100] = (255,125,0)
img3[100:200] = (0,255,0)
img3[200:300] = (255,0,255)

In [78]:
img3.shape

(300, 300, 3)

In [79]:
type(img3)

numpy.ndarray

In [83]:
new = numpy.hstack((img2,img3))

In [86]:
#new.shape
cv2.imshow('image',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

(100, 300, 3)

In [135]:
ar = numpy.zeros((500,400,3))

In [136]:
ar[100:400,100:200] = (125,125,120)

In [123]:
ar

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.]],

       [[  0.,   0.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.]],

       [[  0.,   0.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.]],

       [[  0.,   0.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.],
        [  0., 125.,   0.]]])

In [137]:
cv2.imshow('image',ar)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [163]:
import cv2

In [164]:
photo = cv2.imread('john.jpeg')

In [165]:
photo2 = cv2.imread('unkn.jpeg')

In [147]:
photo.shape

(194, 259, 3)

In [148]:
photo2.shape

(189, 267, 3)

In [21]:
photo[100:200,100:200],photo2[100:200,100:200] = photo2[100:200,100:200],photo[100:200,100:200]

In [29]:
cv2.imshow('image',photo2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [149]:
rphoto = cv2.rectangle(photo, (100,0),(170,100), [0,255,0], 2 )

In [150]:
rphoto2 = cv2.rectangle(photo2 , (100,0),(170,100),[0,255,0], 2 )

In [167]:
photo2[0:100,100:170] = photo[20:120,100:170]

In [170]:
cv2.imshow('image',photo)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
photo[20:120,100:170] = photo2[0:100,100:170]

NameError: name 'photo2' is not defined

In [120]:
import cv2

In [130]:
photo1 = cv2.imread('john.jpeg')

In [111]:
photo2 = cv2.imread("unkn.jpeg")

In [60]:
photo1.shape

(194, 259, 3)

In [61]:
photo2.shape

(189, 267, 3)

In [131]:
cp1 = photo1[0:180,0:250]

In [123]:
cp1.shape

(180, 250, 3)

In [64]:
cp2 = photo2[0:180,0:250]

In [65]:
cp2.shape

(180, 250, 3)

In [66]:
import numpy

In [70]:
np = numpy.hstack((cp1,cp2))

In [71]:
np.shape

(180, 500, 3)

In [72]:
cv2.imshow('image',np)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [132]:
clr = cv2.cvtColor(cp1, cv2.COLOR_BGR2XYZ)

In [133]:
hs = numpy.hstack((cp1,clr))

In [134]:
hs.shape

(180, 500, 3)

In [135]:
cv2.imshow('image',hs)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [138]:
#hs[0:100,100:170],hs[0:100,350:420] = hs[0:100,350:420],hs[0:100,100:170]
temp = numpy.copy(hs)
temp[0:100,100:170] = hs[0:100,350:420]
#temp2 = hs[0:100,350:420]
#hs[0:100,350:420] = temp
temp[0:100,350:420] = hs[0:100,100:170]
#hs[0:100,350:420] = temp
cv2.imshow('image',temp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [87]:
clr.shape

(180, 250, 3)

In [50]:
cp1[0:100,100:170],clr[0:100,100:170] = clr[0:100,100:170],cp1[0:100,100:170]

In [51]:
cv2.imshow('image',cp1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
# ---------------------------------collage the images -----------------------------------------------------
import cv2
roman = cv2.imread('roman.jpg')

In [59]:
rom = roman[:,100:600]

In [60]:
rom.shape

(457, 500, 3)

In [61]:
cv2.imshow('image',rom)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
john = cv2.imread('john.jpeg')

In [63]:
john1 = john[0:180,0:250]

In [64]:
unkn = cv2.imread("unkn.jpeg")
unkn1 = unkn[0:180,0:250]

In [65]:
import numpy
both = numpy.hstack((john1,unkn1))

In [66]:
both.shape

(180, 500, 3)

In [67]:
collage = numpy.vstack((rom,both))

In [68]:
cv2.imshow('image',collage)
cv2.waitKey(0)
cv2.destroyAllWindows()
# ---------------------------------------collage end -------------------------------------------

In [139]:
# ---------------------------swap the images ---------------------------------------------------


In [48]:
import cv2


In [49]:
photo1 = cv2.imread('john.jpeg')

In [50]:
photo1.shape

(194, 259, 3)

In [51]:
cp1 = photo1[0:180,0:250]

In [52]:
cp1.shape

(180, 250, 3)

In [53]:
clr = cv2.cvtColor(cp1, cv2.COLOR_BGR2XYZ)

In [54]:
hs = numpy.hstack((cp1,clr))

In [55]:
cv2.imshow('image',hs)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
# ---------------swap the portion of the image

In [57]:
temp = numpy.copy(hs)
temp[0:100,100:170] = hs[0:100,350:420]
temp[0:100,350:420] = hs[0:100,100:170]
cv2.imshow('image',temp)
cv2.waitKey(0)
cv2.destroyAllWindows()
#---------------------end swapping --------------------------------------------------------

In [148]:
#--------------------------------------------- create the image -----------------------------------------

In [43]:
import numpy
import cv2
img2 = numpy.zeros((300,300,3),numpy.uint8)
img2[:,0:100] = (255,125,0)
img2[:,100:200] = (0,255,0)
img2[:,200:300] = (255,0,255)

In [44]:
img3 = numpy.zeros((300,300,3),numpy.uint8)
img3[0:100] = (255,125,0)
img3[100:200] = (0,255,0)
img3[200:300] = (255,0,255)

In [45]:
img4 = numpy.zeros((300,300,3),numpy.uint8)
img4[:,0:100] = (255,125,0)
img4[:,100:200] = (0,255,0)
img4[:,200:300] = (255,0,255)

In [46]:
new = numpy.hstack((img2,img3,img4))

In [47]:
cv2.imshow('image',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# create the image and save the image in jpg format

In [41]:
img5 = numpy.zeros((500,500,3),numpy.uint8)
img5[0:250,0:250] = (255,125,0)
img5[0:250:,250:500] = (0,255,0)
img5[250:500,250:500] = (255,0,255)
img5[250:500:,0:250] = (0,0,255)

In [42]:
cv2.imshow('image',img5)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
cv2.imwrite("created.jpg" , img5)


True